Mise en place du script pour le build de l'application
LisangaSoft/pharma pull request #10
Opened 2017-12-11 18:34 UTC by vostrovams

ce pull request regorge principalement le script grunt pour la contruction de l'application. j'ai également contribué dans les dépendances de developpement dans le fichier package.json; afin de testé mes script j'ai eu également besoin d'une structure de base dans pour le fichier app.js du serveur. à ce stade tout fonctionne comme il faut.

2017-12-11 18:36 UTC, vostrovams commented
je compred pas ce bordel!!! c quoi ça.?????

2017-12-11 19:37 UTC, DedrickEnc requested changes
Ton pull request est bon mais l'intégration semaphore échoue donc cela prouve que tu n'avais pas fait de rebase ou tu as mal utilisé git.
Prière d'ignorer le fichier externe comme `angular.min.js` ...
Et ensuite je pourrais continuer la révision
Merci

2017-12-11 21:38 UTC, vostrovams commented
ok

2017-12-13 18:21 UTC, DedrickEnc reviewed
@vostrovams 

Le travail s'est ameliorE, essaie d'addresser les derniers commentaires et je pourrais melanger ton code.
👍

2017-12-13 18:21 UTC, DedrickEnc commented on package.json
> +    "express": "^4.16.2",
`express` et `mysql` ne sont pas des dependances de developpement.

2017-12-13 18:21 UTC, DedrickEnc commented on client/index.html
> +    <script src="vendors.js"></script>
Pour des raisons de performance, mettre le script dans le `<body>` et non dans le `<head>`

2017-12-13 21:15 UTC, vostrovams commented on package.json
> +    "express": "^4.16.2",
@DedrickEnc c fait

2017-12-13 21:24 UTC, DedrickEnc approved these changes
TMPM
Joli travail

2017-12-13 21:26 UTC, merged